import Foundation

/// 语音识别后处理器
/// 对 SFSpeechRecognizer 的识别结果进行后处理，修正常见的中英文混合识别错误
enum SpeechPostProcessor {
    
    // MARK: - 常见技术术语音译映射表
    
    /// 精确替换映射：错误中文 → 正确英文/术语
    /// 注意：映射顺序很重要，长的、更具体的匹配项应该排在前面
    private static let exactMappings: [(wrong: String, right: String)] = [
        // 技术术语（多字优先）
        ("阿皮哎", "API"),
        ("爱劈唉", "API"),
        ("阿皮", "API"),
        ("诶批艾", "API"),
        ("艾斯迪凯", "SDK"),
        ("埃斯迪凯", "SDK"),
        ("SDK", "SDK"), // 已经是正确的，跳过但保留占位
        ("GitHub", "GitHub"),
        ("github", "GitHub"),
        ("Docker", "Docker"),
        ("docker", "Docker"),
        ("Kubernetes", "Kubernetes"),
        ("kafka", "Kafka"),
        ("Kafka", "Kafka"),
        ("React", "React"),
        ("Vue", "Vue"),
        ("Angular", "Angular"),
        ("Node.js", "Node.js"),
        ("Python", "Python"),
        ("Java", "Java"),
        ("Golang", "Go"),
        ("TypeScript", "TypeScript"),
        ("JavaScript", "JavaScript"),
        ("HTML", "HTML"),
        ("CSS", "CSS"),
        ("SQL", "SQL"),
        ("JSON", "JSON"),
        ("XML", "XML"),
        ("YAML", "YAML"),
        ("URL", "URL"),
        ("URI", "URI"),
        ("HTTP", "HTTP"),
        ("HTTPS", "HTTPS"),
        ("TCP", "TCP"),
        ("UDP", "UDP"),
        ("IP", "IP"),
        ("DNS", "DNS"),
        ("CDN", "CDN"),
        ("VPN", "VPN"),
        ("WiFi", "Wi-Fi"),
        ("Wi-Fi", "Wi-Fi"),
        ("GPU", "GPU"),
        ("CPU", "CPU"),
        ("RAM", "RAM"),
        ("SSD", "SSD"),
        ("HDD", "HDD"),
        ("USB", "USB"),
        ("HDMI", "HDMI"),
        ("OLED", "OLED"),
        ("LED", "LED"),
        ("AI", "AI"),
        ("LLM", "LLM"),
        ("NLP", "NLP"),
        ("CV", "CV"),
        ("ML", "ML"),
        ("DL", "DL"),
        ("RAG", "RAG"),
        ("CRUD", "CRUD"),
        ("REST", "REST"),
        ("RPC", "RPC"),
        ("GRPC", "gRPC"),
        ("OAuth", "OAuth"),
        ("JWT", "JWT"),
        ("SSO", "SSO"),
        ("SaaS", "SaaS"),
        ("PaaS", "PaaS"),
        ("IaaS", "IaaS"),
        ("CI/CD", "CI/CD"),
        ("DevOps", "DevOps"),
        ("MVP", "MVP"),
        ("PRD", "PRD"),
        ("UI", "UI"),
        ("UX", "UX"),
        ("GUI", "GUI"),
        ("CLI", "CLI"),
        ("IDE", "IDE"),
        ("REPL", "REPL"),
        ("SQL", "SQL"),
        ("NoSQL", "NoSQL"),
        ("ORM", "ORM"),
        ("CMS", "CMS"),
        ("CRM", "CRM"),
        ("ERP", "ERP"),
        ("BI", "BI"),
        ("OKR", "OKR"),
        ("KPI", "KPI"),
        ("ROI", "ROI"),
        ("GMV", "GMV"),
        ("DAU", "DAU"),
        ("MAU", "MAU"),
        ("PV", "PV"),
        ("UV", "UV"),
        ("CTR", "CTR"),
        ("CPC", "CPC"),
        ("CPM", "CPM"),
        ("SEO", "SEO"),
        ("SEM", "SEM"),
        ("UGC", "UGC"),
        ("PGC", "PGC"),
        ("OGC", "OGC"),
        ("PUGC", "PUGC"),
        ("B2B", "B2B"),
        ("B2C", "B2C"),
        ("C2C", "C2C"),
        ("O2O", "O2O"),
        
        // 常见英文单词音译
        ("八哥", "bug"),
        ("巴格", "bug"),
        ("Debug", "debug"),
        ("debug", "debug"),
        ("Deploy", "deploy"),
        ("deploy", "deploy"),
        ("Commit", "commit"),
        ("commit", "commit"),
        ("Review", "review"),
        ("review", "review"),
        ("Merge", "merge"),
        ("merge", "merge"),
        ("Branch", "branch"),
        ("branch", "branch"),
        ("PR", "PR"),
        ("Issue", "issue"),
        ("issue", "issue"),
        ("Ticket", "ticket"),
        ("ticket", "ticket"),
        ("欧克", "OK"),
        ("欧凯", "OK"),
        ("OK", "OK"),
        ("Hi", "Hi"),
        ("Hello", "Hello"),
        ("Email", "email"),
        ("email", "email"),
        ("Mail", "mail"),
        ("mail", "mail"),
        ("PM", "PM"),
        ("App", "App"),
        ("APP", "App"),
        ("iPhone", "iPhone"),
        ("iPad", "iPad"),
        ("MacBook", "MacBook"),
        ("Mac", "Mac"),
        ("iOS", "iOS"),
        ("Android", "Android"),
        ("Windows", "Windows"),
        ("Linux", "Linux"),
        ("Ubuntu", "Ubuntu"),
        ("CentOS", "CentOS"),
        ("Debian", "Debian"),
        ("RedHat", "RedHat"),
        ("Fedora", "Fedora"),
        ("Arch", "Arch"),
        ("Vim", "Vim"),
        ("Emacs", "Emacs"),
        ("VS Code", "VS Code"),
        ("Xcode", "Xcode"),
        ("Chrome", "Chrome"),
        ("Safari", "Safari"),
        ("Firefox", "Firefox"),
        ("Edge", "Edge"),
        ("Zoom", "Zoom"),
        ("Slack", "Slack"),
        ("Teams", "Teams"),
        ("钉钉", "钉钉"),
        ("飞书", "飞书"),
        ("企微", "企微"),
        ("微信", "微信"),
        ("微博", "微博"),
        ("小红书", "小红书"),
        ("抖音", "抖音"),
        ("B站", "B站"),
        ("知乎", "知乎"),
        ("淘宝", "淘宝"),
        ("天猫", "天猫"),
        ("京东", "京东"),
        ("拼多多", "拼多多"),
        ("美团", "美团"),
        ("饿了么", "饿了么"),
        ("滴滴", "滴滴"),
        ("高德", "高德"),
        ("百度", "百度"),
        ("谷歌", "Google"),
        ("Google", "Google"),
        ("亚马逊", "Amazon"),
        ("Amazon", "Amazon"),
        ("微软", "Microsoft"),
        ("Microsoft", "Microsoft"),
        ("苹果", "Apple"),
        ("Apple", "Apple"),
        ("特斯拉", "Tesla"),
        ("Tesla", "Tesla"),
        ("Meta", "Meta"),
        ("Facebook", "Facebook"),
        ("Twitter", "Twitter"),
        ("Instagram", "Instagram"),
        ("WhatsApp", "WhatsApp"),
        ("Telegram", "Telegram"),
        ("Line", "Line"),
        ("Kakao", "Kakao"),
        ("Snapchat", "Snapchat"),
        ("TikTok", "TikTok"),
        ("YouTube", "YouTube"),
        ("Netflix", "Netflix"),
        ("Spotify", "Spotify"),
        ("Steam", "Steam"),
        ("Epic", "Epic"),
        ("Unity", "Unity"),
        ("Unreal", "Unreal"),
        ("Blender", "Blender"),
        ("Figma", "Figma"),
        ("Sketch", "Sketch"),
        ("Photoshop", "Photoshop"),
        ("Illustrator", "Illustrator"),
        ("Premiere", "Premiere"),
        ("After Effects", "After Effects"),
        ("Final Cut", "Final Cut"),
        ("Logic Pro", "Logic Pro"),
        ("GarageBand", "GarageBand"),
        ("Notion", "Notion"),
        ("Obsidian", "Obsidian"),
        ("Logseq", "Logseq"),
        ("Roam", "Roam"),
        ("Trello", "Trello"),
        ("Jira", "Jira"),
        ("Confluence", "Confluence"),
        ("GitLab", "GitLab"),
        ("Bitbucket", "Bitbucket"),
        ("Jenkins", "Jenkins"),
        ("GitHub Actions", "GitHub Actions"),
        ("Travis", "Travis"),
        ("CircleCI", "CircleCI"),
        ("SonarQube", "SonarQube"),
        ("Prometheus", "Prometheus"),
        ("Grafana", "Grafana"),
        ("ELK", "ELK"),
        ("Splunk", "Splunk"),
        ("Datadog", "Datadog"),
        ("New Relic", "New Relic"),
        ("Sentry", "Sentry"),
        ("Bugsnag", "Bugsnag"),
        ("PagerDuty", "PagerDuty"),
        ("OpsGenie", "OpsGenie"),
        ("ServiceNow", "ServiceNow"),
        ("Zendesk", "Zendesk"),
        ("Freshdesk", "Freshdesk"),
        ("Intercom", "Intercom"),
        ("HubSpot", "HubSpot"),
        ("Salesforce", "Salesforce"),
        ("Marketo", "Marketo"),
        ("Mailchimp", "Mailchimp"),
        ("SendGrid", "SendGrid"),
        ("Twilio", "Twilio"),
        ("Stripe", "Stripe"),
        ("PayPal", "PayPal"),
        ("Square", "Square"),
        ("Plaid", "Plaid"),
        ("Y Combinator", "Y Combinator"),
        ("YC", "YC"),
        ("a16z", "a16z"),
        ("Sequoia", "Sequoia"),
        ("红杉", "Sequoia"),
        ("高瓴", "Hillhouse"),
        ("IDG", "IDG"),
        ("GGV", "GGV"),
        ("SIG", "SIG"),
        ("Qiming", "Qiming"),
        ("启明", "Qiming"),
        ("ZhenFund", "ZhenFund"),
        ("真格", "ZhenFund"),
        ("高榕", "Gaorong"),
        ("Gaorong", "Gaorong"),
        ("源码", "Source Code"),
        ("五源", "5Y Capital"),
        ("5Y", "5Y Capital"),
        ("顺为", "Shunwei"),
        ("Shunwei", "Shunwei"),
        ("经纬", "Matrix"),
        ("Matrix", "Matrix"),
        ("DCM", "DCM"),
        ("B Capital", "B Capital"),
        ("Tiger", "Tiger"),
        ("老虎", "Tiger"),
        ("Coatue", "Coatue"),
        ("软银", "SoftBank"),
        ("SoftBank", "SoftBank"),
        ("愿景", "Vision Fund"),
        ("金沙江", "GSR"),
        ("GSR", "GSR"),
        ("北极光", "Northern Light"),
        ("创新工场", "Sinovation"),
        ("Sinovation", "Sinovation"),
        ("百度风投", "Baidu Ventures"),
        ("阿里资本", "Alibaba Capital"),
        ("腾讯投资", "Tencent Investment"),
        ("美团龙珠", "Meituan Longzhu"),
        ("字节战投", "ByteDance Investment"),
        ("小米战投", "Xiaomi Investment"),
        ("华为哈勃", "Huawei Hubo"),
        ("宁德时代", "CATL"),
        ("CATL", "CATL"),
        ("比亚迪", "BYD"),
        ("BYD", "BYD"),
        ("蔚来", "NIO"),
        ("NIO", "NIO"),
        ("小鹏", "XPeng"),
        ("XPeng", "XPeng"),
        ("理想", "Li Auto"),
        ("Li Auto", "Li Auto"),
        ("极氪", "Zeekr"),
        ("Zeekr", "Zeekr"),
        ("问界", "AITO"),
        ("AITO", "AITO"),
        ("智界", "Luxeed"),
        ("Luxeed", "Luxeed"),
        ("阿维塔", "Avatr"),
        ("Avatr", "Avatr"),
        ("小米汽车", "Xiaomi Auto"),
        ("零跑", "Leapmotor"),
        ("Leapmotor", "Leapmotor"),
    ]
    
    // MARK: - 后处理入口
    
    /// 对语音识别结果进行后处理修正
    static func postProcess(_ text: String) -> String {
        guard !text.isEmpty else { return text }
        
        var result = text
        
        // 1. 精确替换（长的、具体的匹配项优先）
        // 先按 wrong 字符串长度降序排序，避免短词先匹配导致长词无法匹配
        let sortedMappings = exactMappings.sorted { $0.wrong.count > $1.wrong.count }
        for (wrong, right) in sortedMappings {
            // 跳过已经是正确形式的
            if wrong == right { continue }
            result = result.replacingOccurrences(of: wrong, with: right)
        }
        
        // 2. 处理常见的拼音首字母缩写被识别为中文的情况
        // 例如 "P R" -> "PR"，"A P I" -> "API"
        result = collapseSpacedAcronyms(in: result)
        
        return result
    }
    
    // MARK: - 辅助方法
    
    /// 将空格分隔的大写字母缩写合并（如 "A P I" → "API"）
    private static func collapseSpacedAcronyms(in text: String) -> String {
        // 匹配模式：单个字母/数字 + 空格 + 单个字母/数字，重复2次以上
        let pattern = #"(?<![A-Za-z0-9])([A-Za-z0-9])(?:\s+([A-Za-z0-9])){2,}(?![A-Za-z0-9])"#
        
        guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else {
            return text
        }
        
        let nsRange = NSRange(text.startIndex..., in: text)
        let matches = regex.matches(in: text, options: [], range: nsRange)
        
        var result = text
        // 从后往前替换，避免位置偏移
        for match in matches.reversed() {
            let matchRange = Range(match.range, in: result)!
            let matchedText = String(result[matchRange])
            let collapsed = matchedText.replacingOccurrences(of: " ", with: "")
            result.replaceSubrange(matchRange, with: collapsed)
        }
        
        return result
    }
}
